import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";

const ANALYZING_MESSAGES = [
  "SCANNING TRANSCRIPT PATTERNS...",
  "EXTRACTING BEHAVIORAL SIGNALS...",
  "MAPPING KPI ALIGNMENTS...",
  "CONSULTING NEURAL ENGINE...",
  "SYNTHESIZING FINAL RUBRIC...",
  "GENERATING STRATEGIC INSIGHTS..."
];

export default function Explore() {
  const [transcript, setTranscript] = useState("");
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [showTransition, setShowTransition] = useState(false);
  const [error, setError] = useState(null);
  const [loadingProgress, setLoadingProgress] = useState(0);
  const [currentMsgIndex, setCurrentMsgIndex] = useState(0);

  const analyze = async () => {
    if (!transcript.trim()) return;
    setLoading(true);
    setError(null);
    setResult(null);
    setLoadingProgress(0);
    setCurrentMsgIndex(0);

    // Simulated progress logic for the bar
    const progressInterval = setInterval(() => {
      setLoadingProgress(prev => (prev < 90 ? prev + Math.random() * 5 : prev));
    }, 400);

    const messageInterval = setInterval(() => {
      setCurrentMsgIndex(prev => (prev + 1) % ANALYZING_MESSAGES.length);
    }, 1200);

    try {
      const res = await fetch("http://localhost:8000/analyze", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ transcript }),
      });
      const data = await res.json();
      
      clearInterval(progressInterval);
      clearInterval(messageInterval);
      setLoadingProgress(100);

      if (data.success) {
        setShowTransition(true);
        setTimeout(() => {
          setResult(data.data);
          setShowTransition(false);
          setLoading(false);
        }, 2500);
      } else {
        setError("AI response parse nahi hua. Raw: " + data.raw);
        setLoading(false);
      }
    } catch (e) {
      clearInterval(progressInterval);
      clearInterval(messageInterval);
      setError("Backend se connect nahi ho pa raha. Kya server chal raha hai?");
      setLoading(false);
    }
  };

  const fadeInUp = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5 } }
  };

  if (showTransition) {
    return (
      <div className="app-container" style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', minHeight: '80vh' }}>
        <motion.div 
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          style={{ textAlign: 'center' }}
        >
          <h2 className="gradient-text animate-pulse" style={{ fontSize: '2rem', marginBottom: '30px', fontWeight: '800' }}>DECODING BEHAVIORAL DNA...</h2>
          <div className="loader-bar-container" style={{ margin: '0 auto', width: '300px', height: '4px' }}>
            <motion.div 
              className="loader-bar" 
              initial={{ width: "0%" }}
              animate={{ width: "100%" }}
              transition={{ duration: 2.5, ease: "easeInOut" }}
            />
          </div>
          <p style={{ marginTop: '20px', color: 'var(--text-dim)', letterSpacing: '0.2em', fontSize: '0.7rem' }}>SYNTHESIZING STRATEGIC RUBRIC ALIGNMENT</p>
        </motion.div>
      </div>
    );
  }

  return (
    <div className="app-container">
      
      <motion.header className="header" initial="hidden" animate="visible" variants={fadeInUp}>
        <h1 className="gradient-text" style={{ fontSize: '3rem' }}>Neural Workspace</h1>
        <p style={{ color: 'var(--text-dim)', fontSize: '1rem' }}>Deploying Neural Logic Engines</p>
      </motion.header>

      <motion.main initial="hidden" animate="visible" variants={fadeInUp}>
        
        <div className="warning-bar">
          <span>🛡️</span>
          <span><strong>SECURE DRAFT</strong> — Behavioral insights generated by AI. Review before strategic application.</span>
        </div>

        <section className="glass-card input-section" style={{ padding: '40px' }}>
          <label className="input-label">Raw Supervisor Transcript</label>
          <textarea
            className="transcript-area"
            placeholder="Paste the transcript here for deep behavioral mapping..."
            value={transcript}
            onChange={(e) => setTranscript(e.target.value)}
            style={{ fontSize: '1.1rem' }}
          />
          
          <div style={{ position: 'relative', marginTop: '20px' }}>
            <button
              className={`analyze-btn ${loading ? '' : 'pulse-primary'}`}
              onClick={analyze}
              disabled={loading}
              style={{ width: '100%', padding: '20px' }}
            >
              {loading ? "PROCESSING..." : "INITIATE DEEP ANALYSIS"}
            </button>

            {loading && (
              <motion.div 
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                style={{ marginTop: '30px', textAlign: 'center' }}
              >
                <div className="loader-bar-container" style={{ width: '100%', height: '4px', background: 'rgba(255,255,255,0.05)', borderRadius: '10px' }}>
                  <motion.div 
                    className="loader-bar" 
                    animate={{ width: `${loadingProgress}%` }}
                    style={{ 
                      height: '100%',
                      background: 'linear-gradient(90deg, var(--primary), var(--secondary))',
                      boxShadow: '0 0 15px var(--primary-glow)',
                      borderRadius: '10px'
                    }} 
                  />
                </div>
                <AnimatePresence mode="wait">
                  <motion.p
                    key={currentMsgIndex}
                    initial={{ opacity: 0, y: 5 }}
                    animate={{ opacity: 1, y: 0 }}
                    exit={{ opacity: 0, y: -5 }}
                    style={{ marginTop: '15px', color: 'var(--primary)', fontSize: '0.75rem', fontWeight: '700', letterSpacing: '0.1em' }}
                  >
                    {ANALYZING_MESSAGES[currentMsgIndex]}
                  </motion.p>
                </AnimatePresence>
              </motion.div>
            )}
          </div>
        </section>

        {error && (
          <motion.div className="error-box" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
            <strong>Analysis Failed:</strong> {error}
          </motion.div>
        )}

        <AnimatePresence>
          {result && (
            <motion.div 
              className="results-grid"
              initial="hidden"
              animate="visible"
              variants={{
                visible: { transition: { staggerChildren: 0.15 } }
              }}
            >
              <motion.div className="glass-card result-card" variants={fadeInUp}>
                <h2 className="card-title neon-text">Suggested Score</h2>
                <div className="score-display">
                  <span className="score-value">{result.score?.value}</span>
                  <span className="score-max">/ 10</span>
                  <span style={{ marginLeft: '15px', fontSize: '1.2rem', color: 'var(--text-main)', fontWeight: '600' }}>— {result.score?.label}</span>
                </div>
                <p style={{ marginTop: '20px', color: 'var(--text-main)', lineHeight: '1.6' }}>
                  <strong>Justification:</strong> {result.score?.justification}
                </p>
              </motion.div>

              <motion.div className="glass-card result-card" variants={fadeInUp}>
                <h3 className="card-title neon-text">Behavioral Evidence</h3>
                <div className="evidence-list">
                  {result.evidence?.map((e, i) => (
                    <div key={i} className={`evidence-item ${e.signal}`}>
                      <p className="evidence-quote">"{e.quote}"</p>
                      <div className="evidence-meta">
                        <strong>{e.signal}</strong> | {e.dimension} | {e.interpretation}
                      </div>
                    </div>
                  ))}
                </div>
              </motion.div>

              <motion.div className="glass-card result-card" variants={fadeInUp}>
                <h3 className="card-title neon-text">Strategic KPI Alignment</h3>
                <div className="kpi-container">
                  {result.kpiMapping?.map((k, i) => (
                    <div key={i} className="kpi-row">
                      <span style={{ fontSize: '0.9rem', color: 'var(--text-main)', marginRight: '15px', lineHeight: '1.5' }}>{k.evidence}</span>
                      <div className="kpi-tag">{k.kpi} • {k.systemOrPersonal}</div>
                    </div>
                  ))}
                </div>
              </motion.div>

              <motion.div className="glass-card result-card" variants={fadeInUp}>
                <h3 className="card-title neon-text">Gap Analysis & Focus</h3>
                <div className="gap-list">
                  {result.gaps?.length === 0 ? (
                    <p style={{ color: 'var(--text-dim)' }}>No critical behavioral gaps detected.</p>
                  ) : (
                    result.gaps?.map((g, i) => (
                      <div key={i} className="gap-item">
                        <strong style={{ color: 'var(--primary)', textTransform: 'uppercase', fontSize: '0.8rem', letterSpacing: '0.1em', display: 'block', marginBottom: '8px' }}>{g.dimension}</strong>
                        <p style={{ fontSize: '0.95rem', color: 'var(--text-main)', lineHeight: '1.6' }}>{g.detail}</p>
                      </div>
                    ))
                  )}
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.main>
    </div>
  );
}
